# Site settings
title: "Andrew Amason"
description: "Sr Manager IT Infrastructure | Technology Leader"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Andrew Amason"
resume_title:                   "Sr Manager IT Infrastructure | Technology Leader"

#Date Formatting

# used for the contact button in _layouts/resume.html
resume_contact_email:           "andrew@andrewamason.tech"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "912-678-2835"
resume_contact_address:         "PO Box 1875, Sylvania GA 30467"

resume_header_contact_info:     "PO Box 1875, Sylvania GA 30467 • 912-678-2835 • andrew@andrewamason.tech"
display_header_contact_info:    "True"

resume_header_intro: "<p>As a seasoned IT Infrastructure leader with over a decade of experience, I have a proven track record in designing, implementing, and managing complex systems across diverse industries. Currently serving as the Senior Manager of IT Infrastructure at CareCentrix Inc., I oversee a team of highly skilled and diverse Server Engineers, drive large-scale projects, and manage vendor relationships to ensure seamless IT operations. My expertise encompasses Microsoft products, VMware & server architecture, Datacenter, storage technologies, as well as corporate cloud infrastructure. I am committed to leveraging my technical acumen and leadership skills to drive innovation and operational excellence in IT infrastructure.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/andrewamason"
  #resume_twitter_url:           "https://twitter.com/andrewamason"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "https://www.facebook.com/andrewamason"
  resume_linkedin_url:          "https://www.linkedin.com/in/andrewamason"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://andrewamason.tech"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

